# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import dropbox_pb2 as proto_dot_dropbox__pb2


class MasterServiceStub(object):
    """Master Service - coordinates storage nodes and file metadata
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/dropbox.MasterService/RegisterNode',
                request_serializer=proto_dot_dropbox__pb2.RegisterRequest.SerializeToString,
                response_deserializer=proto_dot_dropbox__pb2.RegisterResponse.FromString,
                )
        self.RequestPutTargets = channel.unary_unary(
                '/dropbox.MasterService/RequestPutTargets',
                request_serializer=proto_dot_dropbox__pb2.PutTargetsRequest.SerializeToString,
                response_deserializer=proto_dot_dropbox__pb2.PutTargetsResponse.FromString,
                )
        self.AnnounceManifest = channel.unary_unary(
                '/dropbox.MasterService/AnnounceManifest',
                request_serializer=proto_dot_dropbox__pb2.ManifestRequest.SerializeToString,
                response_deserializer=proto_dot_dropbox__pb2.ManifestResponse.FromString,
                )
        self.ListFiles = channel.unary_unary(
                '/dropbox.MasterService/ListFiles',
                request_serializer=proto_dot_dropbox__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=proto_dot_dropbox__pb2.ListFilesResponse.FromString,
                )
        self.GetManifest = channel.unary_unary(
                '/dropbox.MasterService/GetManifest',
                request_serializer=proto_dot_dropbox__pb2.GetManifestRequest.SerializeToString,
                response_deserializer=proto_dot_dropbox__pb2.GetManifestResponse.FromString,
                )
        self.RequestGetTargets = channel.unary_unary(
                '/dropbox.MasterService/RequestGetTargets',
                request_serializer=proto_dot_dropbox__pb2.GetTargetsRequest.SerializeToString,
                response_deserializer=proto_dot_dropbox__pb2.GetTargetsResponse.FromString,
                )


class MasterServiceServicer(object):
    """Master Service - coordinates storage nodes and file metadata
    """

    def RegisterNode(self, request, context):
        """Register a storage node with the master
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestPutTargets(self, request, context):
        """Request storage targets for uploading chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnnounceManifest(self, request, context):
        """Announce file manifest after upload
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """List all files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetManifest(self, request, context):
        """Get manifest for a specific file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestGetTargets(self, request, context):
        """Request storage locations for retrieving chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=proto_dot_dropbox__pb2.RegisterRequest.FromString,
                    response_serializer=proto_dot_dropbox__pb2.RegisterResponse.SerializeToString,
            ),
            'RequestPutTargets': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPutTargets,
                    request_deserializer=proto_dot_dropbox__pb2.PutTargetsRequest.FromString,
                    response_serializer=proto_dot_dropbox__pb2.PutTargetsResponse.SerializeToString,
            ),
            'AnnounceManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.AnnounceManifest,
                    request_deserializer=proto_dot_dropbox__pb2.ManifestRequest.FromString,
                    response_serializer=proto_dot_dropbox__pb2.ManifestResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=proto_dot_dropbox__pb2.ListFilesRequest.FromString,
                    response_serializer=proto_dot_dropbox__pb2.ListFilesResponse.SerializeToString,
            ),
            'GetManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetManifest,
                    request_deserializer=proto_dot_dropbox__pb2.GetManifestRequest.FromString,
                    response_serializer=proto_dot_dropbox__pb2.GetManifestResponse.SerializeToString,
            ),
            'RequestGetTargets': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestGetTargets,
                    request_deserializer=proto_dot_dropbox__pb2.GetTargetsRequest.FromString,
                    response_serializer=proto_dot_dropbox__pb2.GetTargetsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dropbox.MasterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MasterService(object):
    """Master Service - coordinates storage nodes and file metadata
    """

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dropbox.MasterService/RegisterNode',
            proto_dot_dropbox__pb2.RegisterRequest.SerializeToString,
            proto_dot_dropbox__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestPutTargets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dropbox.MasterService/RequestPutTargets',
            proto_dot_dropbox__pb2.PutTargetsRequest.SerializeToString,
            proto_dot_dropbox__pb2.PutTargetsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AnnounceManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dropbox.MasterService/AnnounceManifest',
            proto_dot_dropbox__pb2.ManifestRequest.SerializeToString,
            proto_dot_dropbox__pb2.ManifestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dropbox.MasterService/ListFiles',
            proto_dot_dropbox__pb2.ListFilesRequest.SerializeToString,
            proto_dot_dropbox__pb2.ListFilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dropbox.MasterService/GetManifest',
            proto_dot_dropbox__pb2.GetManifestRequest.SerializeToString,
            proto_dot_dropbox__pb2.GetManifestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestGetTargets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dropbox.MasterService/RequestGetTargets',
            proto_dot_dropbox__pb2.GetTargetsRequest.SerializeToString,
            proto_dot_dropbox__pb2.GetTargetsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class StorageServiceStub(object):
    """Storage Node Service - handles chunk storage
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutChunk = channel.unary_unary(
                '/dropbox.StorageService/PutChunk',
                request_serializer=proto_dot_dropbox__pb2.PutChunkRequest.SerializeToString,
                response_deserializer=proto_dot_dropbox__pb2.PutChunkResponse.FromString,
                )
        self.GetChunk = channel.unary_unary(
                '/dropbox.StorageService/GetChunk',
                request_serializer=proto_dot_dropbox__pb2.GetChunkRequest.SerializeToString,
                response_deserializer=proto_dot_dropbox__pb2.GetChunkResponse.FromString,
                )


class StorageServiceServicer(object):
    """Storage Node Service - handles chunk storage
    """

    def PutChunk(self, request, context):
        """Store a chunk
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChunk(self, request, context):
        """Retrieve a chunk
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PutChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.PutChunk,
                    request_deserializer=proto_dot_dropbox__pb2.PutChunkRequest.FromString,
                    response_serializer=proto_dot_dropbox__pb2.PutChunkResponse.SerializeToString,
            ),
            'GetChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChunk,
                    request_deserializer=proto_dot_dropbox__pb2.GetChunkRequest.FromString,
                    response_serializer=proto_dot_dropbox__pb2.GetChunkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dropbox.StorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StorageService(object):
    """Storage Node Service - handles chunk storage
    """

    @staticmethod
    def PutChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dropbox.StorageService/PutChunk',
            proto_dot_dropbox__pb2.PutChunkRequest.SerializeToString,
            proto_dot_dropbox__pb2.PutChunkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dropbox.StorageService/GetChunk',
            proto_dot_dropbox__pb2.GetChunkRequest.SerializeToString,
            proto_dot_dropbox__pb2.GetChunkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
